name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: "Run generate script"
        run: ./scripts/generate.py android

      - name: "gradlew"
        working-directory: build/android_gradle
        run: chmod +x gradlew

      - name: "Build Android using gradlew."
        working-directory: build/android_gradle
        run: ./gradlew assembleDebug
