name: Build Project

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build Android in ${{ matrix.build_type }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: gradle
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.9
        with:
          key: ${{ github.job }}-${{ matrix.os }}

      - name: "Run generate script"
        run: ./scripts/generate.py android

      - name: "Build Android using gradlew."
        working-directory: build/android_gradle
        run: NDK_CCACHE=1 NDK_CCACHE_BIN=ccache ./gradlew assemble${{ matrix.build_type }}
