name: Build Project

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build Android in ${{ matrix.build_type }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: gradle

      - name: "Run generate script"
        run: ./scripts/generate.py android

      - name: "gradlew"
        working-directory: build/android_gradle
        run: chmod +x gradlew

      - name: "Build Android using gradlew."
        working-directory: build/android_gradle
        run: ./gradlew assemble${{ matrix.build_type }}
